# Generated by Django 4.2.10 on 2025-03-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
