# Generated by Django 4.2.10 on 2025-03-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_paymentrequest_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
