# Generated by Django 4.2.10 on 2025-04-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_paymentrequest_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
