# Generated by Django 4.2.10 on 2025-04-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='message',
        ),
    ]
